
version: '3.8'

services:
  voice-to-text:
    container_name: Voice-To-Text
    build: .
    image: vosk-voice-to-text
    ports:
      - "5000:5000"
    volumes:
      - ./model:/app/model:ro
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40sx
